ws.FogBugz.ALL_COLUMNS = {
    c  : true ,
    dtClosed  : true ,
    dtDue  : true ,
    dtFixFor  : true ,
    dtLastUpdated  : true ,
    dtLastView  : true ,
    dtOpened  : true ,
    dtResolved  : true ,
    fForwarded  : true ,
    fOpen  : true ,
    fReplied  : true ,
    fScoutStopReporting  : true ,
    fSubscribed  : true ,
    hrsCurrEst  : true ,
    hrsElapsed  : true ,
    hrsOrigEst  : true ,
    ixArea  : true ,
    ixBug  : true , 
    ixBugEventLastView  : true ,
    ixBugEventLatest  : true ,
    ixBugEventLatestText  : true ,
    ixCategory  : true ,
    ixDiscussTopic  : true ,
    ixFixFor  : true ,
    ixGroup  : true ,
    ixMailbox  : true ,
    ixPersonAssignedTo  : true ,
    ixPersonClosedBy  : true ,
    ixPersonLastEditedBy  : true ,
    ixPersonOpenedBy  : true ,
    ixPersonResolvedBy  : true ,
    ixPriority  : true ,
    ixProject  : true ,
    ixRelatedBugs  : true ,
    ixStatus  : true ,
    sArea  : true ,
    sCategory  : true ,
    sComputer  : true ,
    sCustomerEmail  : true ,
    sEmailAssignedTo  : true ,
    sFixFor  : true ,
    sLatestTextSummary  : true ,
    sPersonAssignedTo  : true ,
    sPriority  : true ,
    sProject  : true ,
    sReleaseNotes  : true ,
    sScoutDescription  : true ,
    sScoutMessage  : true ,
    sStatus  : true ,
    sTicket  : true ,
    sTitle  : true ,
    sVersion : true
};

ws.FogBugz.ALL_COLUMNS_STRING = ws.FogBugz.ALL_COLUMNS.keySet().join( "," );
